# Generated by Django 5.0.7 on 2024-07-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("category", "name"),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
